### ISSUE TITLE
Crashes in my modpack when reaches main menu.

### ISSUE THREAD

**Issue by alxpettit** [MineLittlePony/MineLittlePony#173]
It gets all the way through the loading process, briefly shows the loading screen, and then crashes there. Most likely in its attempt to mixin the GUI, I think.

See crash report [here](https://paste.ee/p/JX3nk). I think it's a conflict between Mine Little Pony and something I added recently.

**Comment by killjoy1221** [comment]
Looks like it might be an incompatibility between mson and LilTater.
```
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_824.md7f3490$lambda$init$0$0(class_824.java:542) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_252]
	at net.fabricmc.fabric.impl.client.renderer.registry.BlockEntityRendererRegistryImpl.setup(BlockEntityRendererRegistryImpl.java:40) ~[26794288-be34-4f43-88ef-9569e97b27f8.jar:?]
	at net.minecraft.class_824.handler$bjb009$init(class_824.java:542) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_824.<init>(class_824.java:60) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_824.<clinit>(class_824.java:30) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.minelittlepony.mson.impl.PendingEntityRendererRegistry.initialize(PendingEntityRendererRegistry.java:57) ~[c1828cef-566e-4bd2-9053-393325b66f7a.jar:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_252]
	... 233 more
Caused by: java.lang.NullPointerException
	at mods.ltr.entities.LilTaterBlockEntityRenderer.<clinit>(LilTaterBlockEntityRenderer.java:44) ~[LilTaterReloaded-1.1.7+1.16.1.jar:?]
	at net.minecraft.class_824.md7f3490$lambda$init$0$0(class_824.java:542) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_252]
	at net.fabricmc.fabric.impl.client.renderer.registry.BlockEntityRendererRegistryImpl.setup(BlockEntityRendererRegistryImpl.java:40) ~[26794288-be34-4f43-88ef-9569e97b27f8.jar:?]
	at net.minecraft.class_824.handler$bjb009$init(class_824.java:542) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_824.<init>(class_824.java:60) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_824.<clinit>(class_824.java:30) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at com.minelittlepony.mson.impl.PendingEntityRendererRegistry.initialize(PendingEntityRendererRegistry.java:57) ~[c1828cef-566e-4bd2-9053-393325b66f7a.jar:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0_252]
	... 233 more
```

**Comment by alxpettit** [comment]
I'll test this
