### ISSUE TITLE
Crashes at startup when using LiteLoader and Forge

### ISSUE THREAD

**Issue by ColtonDRG** [MineLittlePony/MineLittlePony#19]
I'm trying to run MineLP on LiteLoader and Forge on Minecraft 1.10.2. Everything works fine under LiteLoader only. I installed the latest Forge from the official website and dragged the latest universal LiteLoader jar into minecraft/mods/1.10.2. To verify that MineLP was in fact the problem, I verified that it still starts with no mods, and it still crashes with MineLP being the only mod. Crash report with MineLP being the only mod below.

My operating system is macOS 10.11, if that's relevant.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 10/2/16 10:45 AM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderPlayer
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:504)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.RenderPlayer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:538)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:185)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixin.minelp.json:MixinRenderPlayer] from phase [DEFAULT] in config [mixin.minelp.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:815)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:768)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:530)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_147923_a was not located in the target class
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:176)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:158)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:959)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:231)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:749)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:719)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:527)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:504)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 170745368 bytes (162 MB) / 715739136 bytes (682 MB) up to 4281597952 bytes (4083 MB)
	Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@5d7ef009
	LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@7dc2e4be
	LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@1c694e60
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2011 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2011.jar) 
	UCH	Forge{12.18.1.2011} [Minecraft Forge] (forge-1.10.2-12.18.1.2011.jar) 
	UCH	minelp_forge{1.10.2.2} [MineLP Forge Hooks] (mod-minelittlepony-1.10.2.2-mc1.10.2.litemod) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.11.13 346.03.15f02' Renderer: 'NVIDIA GeForce GTX 650 OpenGL Engine'
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2011
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GTX 650 OpenGL Engine GL version 2.1 NVIDIA-10.11.13 346.03.15f02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vanilla,squidhq'
	Type: Client (map_client.txt)
	Resource Packs: Matmos.Default.zip, pf-resource-1.10.zip, PureBDcraft 128x MC110.zip, PureBDcraft More 3D Items MC110.zip, PureBDcraft More 3D Blocks MC110.zip, PureBDcraft Technology MC110.zip, PureBDcraft Extra Optifine MC110.zip
	Current Language: Pirate Speak (PIRATE)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
```

**Comment by killjoy1221** [comment]
Duplicate #14. Update forge (2020 or later).

**Comment by ColtonDRG** [comment]
Oh, sorry, I assumed that 2010 was the latest available. I'll check on it. :+1:
