### ISSUE TITLE
1.18.2 crash - java.lang.StackOverflowError: Delayed StackOverflowError due to ReservedStackAccess annotated method

### ISSUE THREAD

**Issue by sudofox** [MineLittlePony/MineLittlePony#197]
```
java.lang.StackOverflowError: Delayed StackOverflowError due to ReservedStackAccess annotated method
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.63)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1026)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
	at net.minecraft.entity.data.DataTracker.getEntry(DataTracker:101)
	at net.minecraft.entity.data.DataTracker.get(DataTracker:118)
	at net.minecraft.entity.LivingEntity.getSleepingPosition(LivingEntity:3231)
	at net.minecraft.entity.LivingEntity.isSleeping(LivingEntity:3243)
	at com.minelittlepony.client.render.EquineRenderManager.getFrustrum(EquineRenderManager.java:56)
	at com.minelittlepony.client.render.entity.PlayerPonyRenderer.shouldRender(PlayerPonyRenderer.java:123)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.shouldRender(PlayerEntityRenderer:543)
	at com.minelittlepony.client.render.entity.PlayerPonyRenderer.shouldRender(PlayerPonyRenderer.java:123)
        <last two lines repeat many times>
```

Not sure why NEC says 1.17.1+build.63

Here's the report on crashy: https://crashy.net/huFH5Z8CwF34qkYZ6Rdv

I did try disabling Iris, which was turned on before.

**Comment by Sollace** [comment]
Please upload your crashlog that we can use to view it. (crashy doesn't seem to work)

Also if you can remove Not Enough Crashes, please, that would help.

**Comment by sudofox** [comment]
Here ya go. Turned off NEC and a few others that could be causing issues, same stacktrace though.

Happens when I load into a world.

[crash-2022-04-08_16.35.36-client.txt](https://github.com/MineLittlePony/MineLittlePony/files/8455166/crash-2022-04-08_16.35.36-client.txt)

**Comment by sudofox** [comment]
Okay, this issue is caused by **Figura**. We can probably close this issue, unless you want to try finding a way to make both of them work together.

**Comment by Sollace** [comment]
Yeah, I remember this issue coming up with Figura before. I believe it's because they override the method in their mixin which causes our code to break (a call to super.method() ends up resolving to this.method() and it becomes an infinite loop).

I can't fix it from my side, unfortunately. 

What I can suggest is try updating Figura or otherwise report the issue to them. I believe they were already made aware of this at some point in 1.17, but I may be mis-remembering.

**Comment by sudofox** [comment]
figura dev closed my issue with a new commit, said "mod is still incompatible, but this issue in specific (the crash) was fixed"

whatever that means lol, i'll test it later and update this issue

**Comment by Sollace** [comment]
I'm not entirely sure what Figura does, tbh. They mention avatars.

It looks like they might be doing stuff with the player model, so I presume we override their models with ponies and that's the incompatibility they mention.

If that's the case, it should be fine if you set the pony level to "both" so players without pony skins will use the normal rendering.

When I'm able I'll try getting both installed to see what happens.

**Comment by sudofox** [comment]
Figura basically lets you import blockbench models and apply them over your player model (or alter the player model itself, I've only done very simple things with Figura though). There's some scripting you can do with it too to add responsive physics and whatnot.
