### ISSUE TITLE
Zombie villagers may crash the game

### ISSUE THREAD

**Issue by KostarSf** [MineLittlePony/MineLittlePony#208]
This crash appeared after villagers' models change

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 09.08.2022, 23:31
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "com.minelittlepony.client.model.PlayerModelKey.getKey(boolean)" because the return value of "com.minelittlepony.client.model.ModelType.getPlayerModel(com.minelittlepony.api.pony.meta.Race)" is null
	at com.minelittlepony.client.render.entity.npc.AbstractNpcRenderer.createModel(AbstractNpcRenderer.java:63)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at com.minelittlepony.client.render.entity.npc.AbstractNpcRenderer.render(AbstractNpcRenderer.java:57)
	at com.minelittlepony.client.render.entity.npc.ZomponyVillagerRenderer.render(ZomponyVillagerRenderer.java:1)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer.java:32)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:148)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1274)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1092)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1024)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:833)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1074)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minelittlepony.client.render.entity.npc.AbstractNpcRenderer.createModel(AbstractNpcRenderer.java:63)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at com.minelittlepony.client.render.entity.npc.AbstractNpcRenderer.render(AbstractNpcRenderer.java:57)
	at com.minelittlepony.client.render.entity.npc.ZomponyVillagerRenderer.render(ZomponyVillagerRenderer.java:1)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer.java:32)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:148)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1274)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1092)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1024)

-- Entity being rendered --
Details:
	Entity Type: minecraft:zombie_villager (net.minecraft.entity.mob.ZombieVillagerEntity)
	Entity ID: 221
	Entity Name: Zombie Villager
	Entity's Exact location: -8.50, -60.00, 6.50
	Entity's Block location: World: (-9,-60,6), Section: (at 7,4,6 in -1,-4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:148)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1274)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1092)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1024)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:833)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1074)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Renderer details --
Details:
	Assigned renderer: com.minelittlepony.client.render.entity.npc.ZomponyVillagerRenderer@410a1e0a
	Location: 2.60,-1.80,2.34 - World: (2,-2,2), Section: (at 2,14,2 in 0,-1,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 130.78125
	Delta: 0.4799911
Stacktrace:
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:148)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1274)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1092)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1024)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:833)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1074)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player603'/1, l='ClientLevel', x=-10.99, y=-59.37, z=4.04]]
	Chunk stats: 961, 612
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 724 game time, 724 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:424)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2053)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:742)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Eclipse Adoptium
	Memory: 387951608 bytes (369 MiB) / 2569011200 bytes (2450 MiB) up to 4269801472 bytes (4072 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-8350 Eight-Core Processor           
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 4,34
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GT 730
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1287
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,07
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,07
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096,00
	Memory slot #2 clockSpeed (GHz): 1,07
	Memory slot #2 type: DDR3
	Virtual memory max (MB): 18712,18
	Virtual memory used (MB): 16560,48
	Swap memory total (MB): 2432,00
	Swap memory used (MB): 361,23
	JVM Flags: 4 total; -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=localhost:59570,server=n,suspend=y -XX:+ShowCodeDetailsInExceptionMessages
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GT 730/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: 1920x1027
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayerEntity['Player603'/1, l='ServerLevel[New World]', x=-10.99, y=-59.37, z=4.04]]
	Data Packs: vanilla
	World Generation: Stable
```

**Comment by KostarSf** [comment]
This crash caused by this broken zombie pony texture: 
https://github.com/MineLittlePony/MineLittlePony/blob/1.19/src/main/resources/assets/minelittlepony/textures/entity/zombie_villager/zombie_pony/plains/fletcher.png
