### ISSUE TITLE
Game Crash [1.20.4]

### ISSUE THREAD

**Issue by Qoolize** [MineLittlePony/MineLittlePony#264]
Hello!

Today I installed the 1.20.4 version of MC as I always wait for the updates of other mods.
Is a mob in view, MC crashed.

LOG:

> [19:24:23] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:253) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1945) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1498) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1598) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:1221) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.optifine.render.RenderPositions.getPositionRender()" because "modelpart$vertex.renderPositions" is null
	at net.minecraft.class_630$class_628.compile(class_630.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_630.method_22702(class_630.java:334) ~[client-intermediary.jar:?]
	at net.minecraft.class_630.render(class_630.java:240) ~[client-intermediary.jar:?]
	at net.minecraft.class_630.render(class_630.java:249) ~[client-intermediary.jar:?]
	at net.minecraft.class_630.method_22699(class_630.java:202) ~[client-intermediary.jar:?]
	at com.minelittlepony.client.model.part.PonyTail$Segment.render(PonyTail.java:121) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.model.part.PonyTail.renderPart(PonyTail.java:94) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.model.AbstractPonyModel.lambda$forPart$1(AbstractPonyModel.java:82) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.util.render.RenderList$Impl.lambda$accept$0(RenderList.java:65) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.minelittlepony.client.util.render.RenderList$Impl.accept(RenderList.java:65) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.model.AbstractPonyModel.lambda$withStage$2(AbstractPonyModel.java:95) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.util.render.RenderList$Impl.lambda$accept$0(RenderList.java:65) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.minelittlepony.client.util.render.RenderList$Impl.accept(RenderList.java:65) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.model.AbstractPonyModel.method_2828(AbstractPonyModel.java:88) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:210) ~[client-intermediary.jar:?]
	at net.minecraft.class_927.method_4072(class_927.java:55) ~[client-intermediary.jar:?]
	at com.minelittlepony.client.render.entity.AbstractPonyRenderer.method_4072(AbstractPonyRenderer.java:72) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at com.minelittlepony.client.render.entity.AbstractPonyRenderer.method_3936(AbstractPonyRenderer.java:31) ~[minelittlepony-4.11.5+1.20.2.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:190) ~[client-intermediary.jar:?]
	... 18 more

So.. yes. If needed more information or from the log, let me know.

~Qoo

**Comment by MimzyFang** [comment]
could you post the full log file

**Comment by Qoolize** [comment]
Hello!
Yes. The first three times I couldn't save a log because it crashed immediately.. But here:

  ---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-02-01 19:24:30
Description: Rendering entity in world

>java.lang.NullPointerException: Cannot invoke "net.optifine.render.RenderPositions.getPositionRender()" because "modelpart$vertex.renderPositions" is null
	at net.minecraft.class_630$class_628.compile(class_630.java:824)
	at net.minecraft.class_630.method_22702(class_630.java:334)
	at net.minecraft.class_630.render(class_630.java:240)
	at net.minecraft.class_630.render(class_630.java:249)
	at net.minecraft.class_630.method_22699(class_630.java:202)
	at com.minelittlepony.client.model.part.PonyTail$Segment.render(PonyTail.java:121)
	at com.minelittlepony.client.model.part.PonyTail.renderPart(PonyTail.java:94)
	at com.minelittlepony.client.model.AbstractPonyModel.lambda$forPart$1(AbstractPonyModel.java:82)
	at com.minelittlepony.client.util.render.RenderList$Impl.lambda$accept$0(RenderList.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.minelittlepony.client.util.render.RenderList$Impl.accept(RenderList.java:65)
	at com.minelittlepony.client.model.AbstractPonyModel.lambda$withStage$2(AbstractPonyModel.java:95)
	at com.minelittlepony.client.util.render.RenderList$Impl.lambda$accept$0(RenderList.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.minelittlepony.client.util.render.RenderList$Impl.accept(RenderList.java:65)
	at com.minelittlepony.client.model.AbstractPonyModel.method_2828(AbstractPonyModel.java:88)
	at net.minecraft.class_922.method_4054(class_922.java:210)
	at net.minecraft.class_927.method_4072(class_927.java:55)
	at com.minelittlepony.client.render.entity.AbstractPonyRenderer.method_4072(AbstractPonyRenderer.java:72)
	at com.minelittlepony.client.render.entity.AbstractPonyRenderer.method_3936(AbstractPonyRenderer.java:31)
	at net.minecraft.class_898.method_3954(class_898.java:190)
	at net.minecraft.class_761.method_22977(class_761.java:1945)
	at net.minecraft.class_761.method_22710(class_761.java:1498)
	at net.minecraft.class_757.method_3188(class_757.java:1598)
	at net.minecraft.class_757.method_3192(class_757.java:1221)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


>A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
>Thread: Render thread
Stacktrace:
	at net.minecraft.class_630$class_628.compile(class_630.java:824)
	at net.minecraft.class_630.method_22702(class_630.java:334)
	at net.minecraft.class_630.render(class_630.java:240)
	at net.minecraft.class_630.render(class_630.java:249)
	at net.minecraft.class_630.method_22699(class_630.java:202)
	at com.minelittlepony.client.model.part.PonyTail$Segment.render(PonyTail.java:121)
	at com.minelittlepony.client.model.part.PonyTail.renderPart(PonyTail.java:94)
	at com.minelittlepony.client.model.AbstractPonyModel.lambda$forPart$1(AbstractPonyModel.java:82)
	at com.minelittlepony.client.util.render.RenderList$Impl.lambda$accept$0(RenderList.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.minelittlepony.client.util.render.RenderList$Impl.accept(RenderList.java:65)
	at com.minelittlepony.client.model.AbstractPonyModel.lambda$withStage$2(AbstractPonyModel.java:95)
	at com.minelittlepony.client.util.render.RenderList$Impl.lambda$accept$0(RenderList.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.minelittlepony.client.util.render.RenderList$Impl.accept(RenderList.java:65)
	at com.minelittlepony.client.model.AbstractPonyModel.method_2828(AbstractPonyModel.java:88)
	at net.minecraft.class_922.method_4054(class_922.java:210)
	at net.minecraft.class_927.method_4072(class_927.java:55)
	at com.minelittlepony.client.render.entity.AbstractPonyRenderer.method_4072(AbstractPonyRenderer.java:72)
	at com.minelittlepony.client.render.entity.AbstractPonyRenderer.method_3936(AbstractPonyRenderer.java:31)
	at net.minecraft.class_898.method_3954(class_898.java:190)
	at net.minecraft.class_761.method_22977(class_761.java:1945)
	at net.minecraft.class_761.method_22710(class_761.java:1498)
	at net.minecraft.class_757.method_3188(class_757.java:1598)

-- Entity being rendered --
>Details:
	Entity Type: minecraft:villager (net.minecraft.class_1646)
	Entity ID: 21
	Entity Name: Dorfbewohner
	Entity's Exact location: 212.27, 100.00, 99.55
	Entity's Block location: World: (212,100,99), Section: (at 4,4,3 in 13,6,6; chunk contains blocks 208,-64,96 to 223,319,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: -0.04, -0.08, 0.06
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:190)
	at net.minecraft.class_761.method_22977(class_761.java:1945)
	at net.minecraft.class_761.method_22710(class_761.java:1498)
	at net.minecraft.class_757.method_3188(class_757.java:1598)
	at net.minecraft.class_757.method_3192(class_757.java:1221)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Renderer details --
>Details:
	Assigned renderer: com.minelittlepony.client.render.entity.npc.VillagerPonyRenderer@7579be99
	Location: 0.47,-1.62,-10.76 - World: (0,-2,-11), Section: (at 0,14,5 in 0,-1,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: 37.96875
	Delta: 0.63880813
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:190)
	at net.minecraft.class_761.method_22977(class_761.java:1945)
	at net.minecraft.class_761.method_22710(class_761.java:1498)
	at net.minecraft.class_757.method_3188(class_757.java:1598)
	at net.minecraft.class_757.method_3192(class_757.java:1221)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Uptime --
>Details:
	JVM uptime: 85.621s
	Wall uptime: 60.219s
	High-res time: 52.966s
	Client ticks: 340 ticks / 17.000s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
>Details:
	All players: 1 total; [class_746['Qoolize'/18, l='ClientLevel', x=211.81, y=100.00, z=110.32]]
	Chunk stats: 441, 249
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,100,0), Section: (at 0,4,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 86010 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 36

-- Last reload --
>Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterf3, bigpony, cloth-config, command-block-ide, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, freecam, g4mespeed, g4mespeed-ui, minelp, mm, modmenu, mson, optifabric, worldedit, worldeditcui, xaerominimap, xaeroworldmap

Fabric Mods:
>betterf3: BetterF3 9.0.0
cloth-config: Cloth Config v13 13.0.114
cloth-basic-math: cloth-basic-math 0.6.1
bigpony: Big Pony 1.11.1+1.20.2
command-block-ide: Command Block IDE 0.4.5
fabric-api: Fabric API 0.95.4+1.20.4
fabric-api-base: Fabric API Base 0.4.36+78d798af4f
fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.48+82b1bb3e4f
fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.12+78d798af4f
fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.2+25e1b4764f
fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.1+5c0133444f
fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.73+df3654b34f
fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.23+78d798af4f
fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.31+eabbae364f
fabric-loot-api-v2: Fabric Loot API (v2) 2.1.7+78d798af4f
fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.62+78d798af4f
fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.11+06274a474f
fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.52+df3654b34f
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.33+78d798af4f
fabric-rendering-v0: Fabric Rendering (v0) 1.1.55+df3654b34f
fabric-rendering-v1: Fabric Rendering (v1) 3.1.0+0d29db764f
fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.18+b66dcf784f
fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.9+e84342304f
fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
fabricloader: Fabric Loader 0.15.6
mixinextras: MixinExtras 0.3.2
freecam: Freecam 1.2.2
g4mespeed: G4mespeed 1.4.6
g4mespeed-ui: G4mespeed UI 0.9.10
java: Java HotSpot(TM) 64-Bit Server VM 17
kirin: Kirin UI 1.17.0+1.20.4
minecraft: Minecraft 1.20.4
minelp: Mine Little Pony 4.11.5+1.20.2
mson: Mson 1.9.2
modmenu: Mod Menu 9.0.0
optifabric: OptiFabric 1.14.3
mm: Manningham Mills 2.3
optifabric-libs: OptiFabric Libraries 1.14.3
worldedit: WorldEdit 7.3.0-beta-03+d6d222e
worldeditcui: WorldEditCUI 1.20.3+01
xaerominimap: Xaero's Minimap 23.9.7
xaeroworldmap: Xaero's World Map 1.37.8
Launched Version: 1.20.4
Backend library: LWJGL version 3.3.2-snapshot
Backend API: NVIDIA GeForce GTX 770/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
Window size: 1920x1058
GL Caps: Using framebuffer using OpenGL 3.2
GL debug messages: 
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'optifine'; Server brand changed to 'fabric'
Universe: 400921fb54442d18
Type: Integrated Server (map_client.txt)
Graphics mode: fast
Render Distance: 7/7 chunks
Resource Packs: vanilla, fabric
Current Language: de_de
Locale: en_DE
CPU: 4x AMD FX(tm)-4100 Quad-Core Processor 
Server Running: true
Player Count: 1 / 8; [class_3222['Qoolize'/18, l='ServerLevel[Bunker des Redstones]', x=211.81, y=100.00, z=110.32]]
Data Packs: vanilla, fabric, fabric-convention-tags-v1
Enabled Feature Flags: minecraft:vanilla
World Generation: Stable
OptiFine Version: OptiFine_1.20.4_HD_U_I7_pre2
OptiFine Build: 20231222-174400
Render Distance Chunks: 7
Mipmaps: 0
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 3.2.0 NVIDIA 472.12
OpenGlRenderer: NVIDIA GeForce GTX 770/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4

-- OptiFabric --
>Details:
	OptiFine jar designed for: 1.20.4
	OptiFine jar version: OptiFine_1.20.4_HD_U_I7_pre2
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: D:/Spiele/Minecraft/MultiMC/instances/1.20.4/.minecraft/.optifine/OptiFine_1.20.4_HD_U_I7_pre2/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by MimzyFang** [comment]
ah probably some issue with optifine:
OptiFine doesn't support Fabric natively and is widely known to cause compatibility issues with other mods, including Mine Little Pony, because of this.
For that reason we do not recommend using it if at all possible.

For performance, use: https://modrinth.com/mod/sodium
For Shaders, use: https://irisshaders.net/

These mods, among others that replace Optifine's features, can be found on this list here:
https://lambdaurora.dev/optifine_alternatives

**Comment by MimzyFang** [comment]
this looks like it's solved
