### ISSUE TITLE
Mod crashes game immediately on loading a world or joining a server.

### ISSUE THREAD

**Issue by booblebobble** [MineLittlePony/MineLittlePony#4]
Dump:

---- Minecraft Crash Report ----
// Oops.

Time: 5/19/16 8:38 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at com.brohoof.minelittlepony.Pony.checkMeta(Pony.java:81)
	at com.brohoof.minelittlepony.Pony.<init>(Pony.java:47)
	at com.brohoof.minelittlepony.PonyManager.getPonyFromResourceRegistry(PonyManager.java:68)
	at com.brohoof.minelittlepony.PonyManager.getPonyFromResourceRegistry(PonyManager.java:86)
	at buh.updateModel(SourceFile:182)
	at buh.handler$onDoRender$0(SourceFile:70)
	at buh.a(SourceFile)
	at buh.a(SourceFile:28)
	at brj.redirect$onRenderEntity$0(RenderManager.java:41)
	at brj.a(RenderManager.java:378)
	at brj.a(RenderManager.java:362)
	at bnl.a(RenderGlobal.java:792)
	at bnd.a(EntityRenderer.java:1726)
	at bnd.b(EntityRenderer.java:1555)
	at bnd.a(EntityRenderer.java:1334)
	at bcd.av(SourceFile:992)
	at bcd.a(SourceFile:399)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at magic.launcher.Launcher.main(SourceFile:214)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.brohoof.minelittlepony.Pony.checkMeta(Pony.java:81)
	at com.brohoof.minelittlepony.Pony.<init>(Pony.java:47)
	at com.brohoof.minelittlepony.PonyManager.getPonyFromResourceRegistry(PonyManager.java:68)
	at com.brohoof.minelittlepony.PonyManager.getPonyFromResourceRegistry(PonyManager.java:86)
	at buh.updateModel(SourceFile:182)
	at buh.handler$onDoRender$0(SourceFile:70)
	at buh.a(SourceFile)
	at buh.a(SourceFile:28)
	at brj.redirect$onRenderEntity$0(RenderManager.java:41)

-- Entity being rendered --
Details:
	Entity Type: null (bmr)
	Entity ID: 103
	Entity Name: Daring_Do
	Entity's Exact location: -90.50, 65.00, 18.04
	Entity's Block location: World: (-91,65,18), Chunk: (at 5,4,2 in -6,1; contains blocks -96,0,16 to -81,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: buh@45f5fdd
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 365.13528
	Delta: 0.2233547
Stacktrace:
	at brj.a(RenderManager.java:378)
	at brj.a(RenderManager.java:362)
	at bnl.a(RenderGlobal.java:792)
	at bnd.a(EntityRenderer.java:1726)
	at bnd.b(EntityRenderer.java:1555)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bmr['Daring_Do'/103, l='MpServer', x=-90.50, y=65.00, z=18.04]]
	Chunk stats: MultiplayerChunkCache: 259, 259
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (28,64,244), Chunk: (at 12,4,4 in 1,15; contains blocks 16,0,240 to 31,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33179 game time, 43838 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 47 total; [yy['Spider'/129, l='MpServer', x=-109.01, y=66.00, z=-60.50], bmr['Daring_Do'/103, l='MpServer', x=-90.50, y=65.00, z=18.04], za['Zombie'/4, l='MpServer', x=-144.35, y=71.00, z=50.75], yw['Skeleton'/5, l='MpServer', x=-152.50, y=73.00, z=55.77], za['Zombie'/133, l='MpServer', x=-92.51, y=69.00, z=-50.02], za['Zombie'/6, l='MpServer', x=-152.92, y=73.00, z=70.15], za['Zombie'/134, l='MpServer', x=-86.50, y=67.00, z=-38.50], yw['Skeleton'/135, l='MpServer', x=-84.91, y=67.00, z=-35.42], yy['Spider'/8, l='MpServer', x=-155.50, y=49.00, z=80.50], vu['Bat'/9, l='MpServer', x=-158.62, y=46.57, z=99.25], yw['Skeleton'/144, l='MpServer', x=-73.64, y=67.00, z=-35.26], yw['Skeleton'/145, l='MpServer', x=-68.00, y=63.00, z=42.35], yy['Spider'/151, l='MpServer', x=-63.70, y=67.00, z=-60.00], vu['Bat'/152, l='MpServer', x=-52.42, y=17.84, z=-38.02], yy['Spider'/153, l='MpServer', x=-59.70, y=66.00, z=14.70], yy['Spider'/154, l='MpServer', x=-48.07, y=71.00, z=16.06], aag['Boat'/155, l='MpServer', x=-58.31, y=62.52, z=36.40], wg['Squid'/156, l='MpServer', x=-55.14, y=62.00, z=35.25], yi['Creeper'/157, l='MpServer', x=-39.85, y=67.00, z=34.53], yi['Creeper'/160, l='MpServer', x=-27.50, y=74.00, z=-50.50], za['Zombie'/161, l='MpServer', x=-20.50, y=70.00, z=-40.50], yw['Skeleton'/162, l='MpServer', x=-19.50, y=72.00, z=-43.50], wg['Squid'/163, l='MpServer', x=-32.53, y=62.00, z=40.60], vu['Bat'/36, l='MpServer', x=-96.43, y=17.01, z=64.49], za['Zombie'/164, l='MpServer', x=-16.63, y=64.00, z=37.24], vu['Bat'/37, l='MpServer', x=-82.40, y=18.44, z=76.68], za['Zombie'/167, l='MpServer', x=-13.50, y=72.00, z=-46.50], yi['Creeper'/42, l='MpServer', x=-73.05, y=63.00, z=86.52], wg['Squid'/48, l='MpServer', x=-52.19, y=62.49, z=51.34], wg['Squid'/49, l='MpServer', x=-52.45, y=61.00, z=58.03], wg['Squid'/50, l='MpServer', x=-53.86, y=61.00, z=58.92], yi['Creeper'/115, l='MpServer', x=-162.50, y=70.00, z=12.50], wg['Squid'/51, l='MpServer', x=-61.04, y=61.49, z=67.50], yi['Creeper'/116, l='MpServer', x=-159.50, y=64.00, z=-10.50], wg['Squid'/52, l='MpServer', x=-57.31, y=61.87, z=66.60], yi['Creeper'/117, l='MpServer', x=-147.50, y=71.00, z=9.50], wg['Squid'/53, l='MpServer', x=-54.17, y=61.51, z=64.71], za['Zombie'/118, l='MpServer', x=-152.50, y=71.00, z=8.50], vu['Bat'/54, l='MpServer', x=-35.59, y=13.64, z=88.74], za['Zombie'/119, l='MpServer', x=-150.25, y=71.00, z=29.48], yi['Creeper'/56, l='MpServer', x=-14.19, y=69.00, z=78.50], yw['Skeleton'/121, l='MpServer', x=-140.50, y=71.00, z=26.50], yi['Creeper'/122, l='MpServer', x=-136.68, y=71.00, z=31.81], yi['Creeper'/123, l='MpServer', x=-140.65, y=71.00, z=36.34], za['Zombie'/124, l='MpServer', x=-138.50, y=71.00, z=38.50], za['Zombie'/125, l='MpServer', x=-136.50, y=71.00, z=35.50], yw['Skeleton'/126, l='MpServer', x=-124.50, y=64.00, z=10.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bks.a(WorldClient.java:478)
	at bcd.b(SourceFile:2521)
	at bcd.a(SourceFile:408)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at magic.launcher.Launcher.main(SourceFile:214)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 325600656 bytes (310 MB) / 500695040 bytes (477 MB) up to 500695040 bytes (477 MB)
	JVM Flags: 3 total; -Xms512m -Xmx512m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.9.4
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.10, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: bcd$7@77b71acd
	OptiFine Version: OptiFine_1.9.4_HD_U_B4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 365.10
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by killjoy1221** [comment]
Fixed in latest commit. b1d17a7

**Comment by killjoy1221** [comment]
You might also want to update liteloader. I discovered a bug (related to offline/non-premium accounts) in it after fixing this.
